name: Mac Build

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Download CEF for Mac (ARM64)
      run: |
        curl -L "https://cef-builds.spotifycdn.com/cef_binary_147.0.10%2Bgd58e84d%2Bchromium-147.0.7727.118_macosarm64_minimal.tar.bz2" -o cef_mac.tar.bz2
        tar xf cef_mac.tar.bz2
        mv cef_binary_147.0.10+gd58e84d+chromium-147.0.7727.118_macosarm64_minimal cef

    - name: Configure CMake
      run: cmake -S . -B build

    - name: Build Project
      run: cmake --build build --config Release

    - name: Package Mac Release
      run: |
        mkdir hqxball-mac
        cp build/hqxball_client hqxball-mac/ || true
        cp -r cef/Release/* hqxball-mac/ || true
        cp -r cef/Resources/* hqxball-mac/ || true
        cp -r assets hqxball-mac/ || true

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: Hqxball-Mac-App
        path: hqxball-mac/
